name: Bug Report 🐞
description: Report any bugs or issues you've encountered.
title: "[🐞 Bug]: "
labels: bug, needs triage
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to report a bug! Please provide as much detail as possible to help us resolve the issue quickly.**

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Clearly describe the issue and its impact.
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: List the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe the error
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What should happen instead of the issue?
      placeholder: "Describe the correct behavior."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?
      placeholder: "Describe the incorrect behavior."

  - type: input
    id: environment
    attributes:
      label: 🖥️ Environment
      description: Provide details about your setup.
      placeholder: "e.g., OS: Windows/Mac/Linux, Node.js version, Browser, etc."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📂 Additional Context or Screenshots
      description: Add any other context or attach screenshots to help us understand the issue.
